Support Pausing
base-cms/parcel-plug pull request #5
Opened 2019-01-17 22:29 UTC by solocommand

Support pausing for line items and ads

2019-01-18 15:43 UTC, solocommand commented
<img width="540" alt="screen shot 2019-01-18 at 9 42 24 am" src="https://user-images.githubusercontent.com/1778222/51396796-7009fd00-1b05-11e9-9214-8b43bbf2aacf.png">
<img width="542" alt="screen shot 2019-01-18 at 9 42 17 am" src="https://user-images.githubusercontent.com/1778222/51396797-70a29380-1b05-11e9-81e7-985d04cfa7cf.png">
<img width="539" alt="screen shot 2019-01-18 at 9 42 02 am" src="https://user-images.githubusercontent.com/1778222/51396798-70a29380-1b05-11e9-9c12-ad60de2d789c.png">
<img width="543" alt="screen shot 2019-01-18 at 9 41 54 am" src="https://user-images.githubusercontent.com/1778222/51396799-70a29380-1b05-11e9-9115-b7a1dd767aa7.png">

2019-01-22 16:22 UTC, solocommand commented
<img width="1166" alt="screen shot 2019-01-22 at 10 21 53 am" src="https://user-images.githubusercontent.com/1778222/51549229-9db9b380-1e2f-11e9-9421-8f87c57b42d3.png">
<img width="1172" alt="screen shot 2019-01-22 at 10 21 38 am" src="https://user-images.githubusercontent.com/1778222/51549231-9db9b380-1e2f-11e9-8e63-478822f8a085.png">

2019-01-22 18:35 UTC, zarathustra323 requested changes

2019-01-22 18:35 UTC, zarathustra323 commented on services/manage/app/components/auto-save/toggle-switch.js
> +    debounceInput(event) {
Debouncing of input isn't needed

2019-01-22 18:35 UTC, zarathustra323 commented on services/manage/app/components/auto-save/toggle-switch.js
> +    debounceChange(event) {
Debouncing of change isn't needed

2019-01-22 18:35 UTC, zarathustra323 commented on services/manage/app/controllers/manage/orders/edit/lineitems/edit/ads/edit.js
> +    if (this.get('isActionRunning')) return true;
Disabling of the switch should just use `disabled={{isActionRunning}}` in the template... or, rather, the autosave switch component should disable itself when running. Then you do not need to use this

2019-01-22 18:35 UTC, zarathustra323 commented on services/manage/app/controllers/manage/orders/edit/lineitems/edit/ads/edit.js
> +    async pause() {
This should take the value directly as an argument, and not use the bound value

2019-01-22 18:35 UTC, zarathustra323 commented on services/manage/app/controllers/manage/orders/edit/lineitems/edit/index.js
> +  isActive: computed.not('model.paused'),
There is not an `isActive()` method on the model schema... perhaps make this a graph field and use instead of a computed property

2019-01-22 18:35 UTC, zarathustra323 commented on services/manage/app/templates/manage/orders/edit/lineitems/edit/ads/edit.hbs
> +          {{lineitem/-fields/paused
This shouldn't use the lineitem paused field and instead should have an ad paused field component

2019-01-22 18:35 UTC, zarathustra323 commented on services/manage/app/controllers/manage/orders/edit/lineitems/edit/index.js
> +    async pause() {
Should use the value directly as an arg, instead of the mode value

2019-01-22 18:35 UTC, zarathustra323 commented on services/manage/app/components/auto-save/toggle-switch.js
> +  typeDelay: 750,
Type delay can be removed

2019-01-22 18:35 UTC, zarathustra323 commented on services/manage/app/controllers/manage/orders/edit/lineitems/edit/ads/edit.js
> +        this.get('graphErrors').show(e);
This should throw the error so the form component can handle it as a validation error message

2019-01-22 18:35 UTC, zarathustra323 commented on services/manage/app/controllers/manage/orders/edit/lineitems/edit/index.js
> +        this.get('graphErrors').show(e);
This should throw the error so the form component can handle it as a validation error message

2019-01-22 18:35 UTC, zarathustra323 commented on services/manage/app/controllers/manage/orders/edit/lineitems/edit/index.js
> +        this.set('isPausing', false);
The `isPausing` would not be necessary if you make the switch auto save component disable itself on save

2019-01-22 18:37 UTC, zarathustra323 commented
@solocommand I know it's annoying, but can you manually add a class to the switch and add custom css to make it the same height/width of the regular input elements?

2019-01-22 19:35 UTC, zarathustra323 requested changes

2019-01-22 19:35 UTC, zarathustra323 commented on services/manage/app/components/auto-save/toggle-switch.js
> +    debounceChange({ target }) {
Debounce change can be removed still :)

2019-01-22 19:35 UTC, zarathustra323 commented on services/manage/app/templates/components/auto-save/toggle-switch.hbs
> +      element=(component "form-elements/input"
Should this use the `form-elements/checkbox` component?

2019-01-22 19:35 UTC, zarathustra323 commented on services/manage/app/templates/components/auto-save/toggle-switch.hbs
> +        change=(action "debounceChange")
Change can fire the sendOnChange directly

2019-01-23 15:33 UTC, zarathustra323 commented
@solocommand I added a few more comments yesterday... just wanted to check if still had any changes to push, or if I should just merge?

2019-01-23 19:53 UTC, zarathustra323 approved these changes

2019-01-23 19:53 UTC, merged